# docker compose up
# docker compose down
# http://localhost:1313
services:
  hugo:
    image: hugomods/hugo:exts
    command: server -D --bind 0.0.0.0
    ports:
      - "1313:1313"
    volumes:
      - .:/src
